import { useState } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { RootState, addItem, deleteItem, updateItem } from '../store';
import { useSearchSort } from '../context/SearchSortContext';
import BottomNav from '../components/BottomNav';

export default function Home() {
  const dispatch = useDispatch();
    const items = useSelector((state: RootState) => state.app.items);
      const user = useSelector((state: RootState) => state.app.user);
        
          const { searchQuery, setSearchQuery, sortBy, setSortBy } = useSearchSort();
            const [showModal, setShowModal] = useState(false);
              const [editingItem, setEditingItem] = useState<any | null>(null);

                const [form, setForm] = useState({ name: '', quantity: 1, category: 'Groceries', notes: '' });

                  const openEditModal = (item: any) => {
                      setEditingItem(item);
                          setForm({ name: item.name, quantity: item.quantity, category: item.category, notes: item.notes || '' });
                              setShowModal(true);
                                };

                                  const handleSave = (e: React.FormEvent) => {
                                      e.preventDefault();
                                          if (editingItem) {
                                                dispatch(updateItem({ ...editingItem, ...form }));
                                                    } else {
                                                          dispatch(addItem({ id: Date.now().toString(), ...form, dateAdded: new Date().toISOString() }));
                                                              }
                                                                  closeFormModal();
                                                                    };

                                                                      const closeFormModal = () => {
                                                                          setShowModal(false);
                                                                              setEditingItem(null);
                                                                                  setForm({ name: '', quantity: 1, category: 'Groceries', notes: '' });
                                                                                    };

                                                                                      const processedItems = items
                                                                                          .filter(item => item.name.toLowerCase().includes(searchQuery.toLowerCase()))
                                                                                              .sort((a, b) => {
                                                                                                    if (sortBy === 'category') return a.category.localeCompare(b.category);
                                                                                                          if (sortBy === 'date') return new Date(a.dateAdded).getTime() - new Date(b.dateAdded).getTime();
                                                                                                                return a.name.localeCompare(b.name);
                                                                                                                    });

                                                                                                                      return (
                                                                                                                          <div className="max-w-md mx-auto min-h-screen bg-gray-50 pb-24 px-4 pt-6">
                                                                                                                                <header className="flex justify-between items-center mb-6">
                                                                                                                                        <div>
                                                                                                                                                  <h1 className="text-xl font-bold">Hi, {user?.name || 'Guest'} 👋</h1>
                                                                                                                                                            <p className="text-xs text-gray-500">Track and manage your everyday lists.</p>
                                                                                                                                                                    </div>
                                                                                                                                                                            <div className="w-10 h-10 rounded-full bg-brandGreen text-white flex items-center justify-center font-bold">
                                                                                                                                                                                      {user?.name?.charAt(0) || 'U'}
                                                                                                                                                                                              </div>
                                                                                                                                                                                                    </header>

                                                                                                                                                                                                          <div className="mb-4 space-y-3">
                                                                                                                                                                                                                  <input type="text" placeholder="🔍 Search items by name..." value={searchQuery} onChange={e => setSearchQuery(e.target.value)} className="w-full p-3 rounded-xl border border-gray-200 bg-white shadow-sm" />
                                                                                                                                                                                                                          <div className="flex gap-2 items-center text-sm">
                                                                                                                                                                                                                                    <span className="text-gray-500 font-medium">Sort By:</span>
                                                                                                                                                                                                                                              {['name', 'category', 'date'].map((opt) => (
                                                                                                                                                                                                                                                          <button key={opt} type="button" onClick={() => setSortBy(opt)} className={`px-3 py-1.5 rounded-lg font-medium capitalize ${sortBy === opt ? 'bg-brandGreen text-white' : 'bg-white text-gray-600 border'}`}>
                                                                                                                                                                                                                                                                        {opt}
                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                  {processedItems.length === 0 ? (
                                                                                                                                                                                                                                                                                                                          <div className="flex flex-col items-center justify-center py-20 text-center">
                                                                                                                                                                                                                                                                                                                                    <span className="text-5xl mb-4">📋</span>
                                                                                                                                                                                                                                                                                                                                              <h3 className="font-bold text-gray-700">Your list is empty</h3>
                                                                                                                                                                                                                                                                                                                                                        <p className="text-gray-400 text-sm max-w-xs mt-1">Add items to configure and build localized multi-category shopping logs.</p>
                                                                                                                                                                                                                                                                                                                                                                  <button type="button" onClick={() => setShowModal(true)} className="mt-6 bg-brandGreen hover:bg-brandGreen-hover text-white px-6 py-2.5 rounded-xl font-medium shadow">
                                                                                                                                                                                                                                                                                                                                                                              + Add Item
                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                              <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                        {processedItems.map(item => (
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={item.id} className="p-4 bg-white rounded-xl shadow-sm border border-gray-100 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h4 className="font-bold text-gray-800">{item.name}</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-xs text-gray-400">Qty: {item.quantity} • <span className="bg-brandGreen-light text-brandGreen font-semibold px-1.5 py-0.5 rounded text-[10px]">{item.category}</span></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {item.notes && <p className="text-xs text-gray-500 italic mt-1">"{item.notes}"</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button type="button" onClick={() => openEditModal(item)} className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg">✏️</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button type="button" onClick={() => dispatch(deleteItem(item.id))} className="p-2 text-red-600 hover:bg-red-50 rounded-lg">🗑️</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button type="button" onClick={() => setShowModal(true)} className="w-full py-3 bg-brandGreen text-white rounded-xl font-bold mt-4 shadow-md hover:bg-brandGreen-hover">+ Add New Item</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {showModal && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="fixed inset-0 bg-black/50 z-50 flex items-end max-w-md mx-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <form onSubmit={handleSave} className="bg-white w-full rounded-t-3xl p-6 space-y-4 shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3 className="text-lg font-bold">{editingItem ? 'Edit Item Details' : 'Add New Item'}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input required type="text" placeholder="Item Name (e.g. Milk)" className="w-full border p-3 rounded-xl bg-gray-50" value={form.name} onChange={e => setForm({...form, name: e.target.value})} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid grid-cols-2 gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="text-xs text-gray-500 block mb-1">Quantity</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input required type="number" min="1" className="w-full border p-3 rounded-xl bg-gray-50" value={form.quantity} onChange={e => setForm({...form, quantity: parseInt(e.target.value) || 1})} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label className="text-xs text-gray-500 block mb-1">Category</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <select className="w-full border p-3 rounded-xl bg-gray-50" value={form.category} onChange={e => setForm({...form, category: e.target.value})}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option>Groceries</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option>Bakery</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option>Fruits</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option>Snacks</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input type="text" placeholder="Notes (Optional)" className="w-full border p-3 rounded-xl bg-gray-50" value={form.notes} onChange={e => setForm({...form, notes: e.target.value})} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex gap-3 pt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="button" onClick={closeFormModal} className="w-1/2 py-3 bg-gray-100 font-medium rounded-xl text-gray-600">Cancel</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button type="submit" className="w-1/2 py-3 bg-brandGreen text-white font-medium rounded-xl shadow hover:bg-brandGreen-hover">Save Item</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <BottomNav />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      